name: buildAndTest
on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  build:
    # use ubuntu for more build minutes
    runs-on: ubuntu-latest
    # use release mode for all steps
    env:
      DOTNET_CONFIG: 'Release'
      DOTNET_DIR: ./c-sharp

    steps:
    - name: clone repo
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.814

      # restore dependencies  
    - name: Install dependencies
      working-directory: ${{ env.DOTNET_DIR }}
      run: dotnet restore

      # build project
    - name: Build
      working-directory: ${{ env.DOTNET_DIR }}
      run: dotnet build --configuration $DOTNET_CONFIG --no-restore

    - name: Test
      working-directory: ${{ env.DOTNET_DIR }}    
      run: dotnet test --no-restore --no-build --configuration $DOTNET_CONFIG
